[[plugins]]
package = "@netlify/plugin-sitemap"

[plugins.inputs]
  buildDir = "public"
  exclude = [
    # By file Path
    './buildDir/public/index.html',
    # By Glob pattern
    '**/**/child-one.html'
  ]
  # disable pretty URLS and keep `index.html` & trailing `.html` file references in paths
  prettyURLs = true
